#!/usr/bin/env bash

# NOTE: _env below gets the 3 vars above directly
eval $(op read op://testing-rw/databricks_ccv2/_env | op inject)

# Create Databricks config
cat >~/.databrickscfg <<EOF
[DEFAULT]
host = $DATABRICKS_ENDPOINT
token = $DATABRICKS_TOKEN
EOF

schema_rand="$(uuidgen | tr '[:upper:]' '[:lower:]' | tr '-' '_' | cut -b1-6)"
export DATABRICKS_WRITE_TEST_CATALOG=duckdb_write_testing
export DATABRICKS_WRITE_TEST_SCHEMA="test_schema_$schema_rand"

exec "$@"
